agent_name: "minimal_memory_agent_qwen_converted"
model_name: "Qwen/Qwen3-4B-Instruct-2507"
enable_thinking: false
vllm: true
thinking_budget: 1024
max_new_tokens: 2048

infer_with_full_memory: true
external_model_url: http://127.0.0.1:8001/v1
api_key: EMPTY
